name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install pipenv
      run: pip install pipenv

    - name: Install dependencies
      run: pipenv install --dev
      working-directory: group11-regex-log-analyzer

    - name: Verify pytest installation
      run: pipenv run python -m pytest --version
      working-directory: group11-regex-log-analyzer

    - name: Run tests
      run: pipenv run python -m pytest
      working-directory: group11-regex-log-analyzer