name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install pipenv
      run: pip install pipenv
      working-directory: group11-regex-log-analyzer

    - name: Install dependencies
      run: pipenv install --dev
      working-directory: group11-regex-log-analyzer

    - name: List installed packages
      run: pipenv run pip list
      working-directory: group11-regex-log-analyzer

    - name: Run tests
      run: pipenv run pytest
      working-directory: group11-regex-log-analyzer